Repository radiantearth/stac-browser, pull requests merged in 2023-08, with the labels that each got.

#358 Config schema etc. (breaking: stacProxyUrl)
  config.js
  config.schema.json
  docs/local_files.md
  docs/options.md
  src/store/index.js
  vue.config.js
Labels: codebase

#359 Allow Collection Search result to be used in Item Search
  src/components/Catalog.vue
  src/components/Catalogs.vue
  src/components/Item.vue
  src/components/Items.vue
  src/components/SearchFilter.vue
  src/components/StacLink.vue
  src/locales/de/texts.json
  src/locales/en/texts.json
  src/store/index.js
  src/views/Catalog.vue
  src/views/Search.vue
Labels: enhancement

#357 Fixes Azimuth typo
  package.json
  src/locales/de/fields.json
  src/locales/en/fields.json
  src/locales/es/fields.json
  src/locales/fr/fields.json
  src/locales/it/fields.json
  src/locales/ro/fields.json
Labels: i18n / l10n
